sudo: required

services:
  - docker

before_install:
  - docker build -t trainning_app .

script:
  - docker run -t trainning_app sh -c "flake8 && python -m pytest ./tests/"

notifications:
  email: false
